### ISSUE TITLE
开发费是否会用代理?

### ISSUE THREAD

**Issue by bjznl** [NebuTech/NBMiner#633]
如果我的nbminer用的是代理服务器挖矿，开发费的抽水是否也会通过代理连接？

**Comment by pdieppa** [comment]
It should!

**Comment by liukaixin007** [comment]
应该不是

**Comment by nebutech-admin** [comment]
设置 -proxy 的话，fee也会跟着走

**Comment by liukaixin007** [comment]
- How to set proxy? Do I need to fill in the wallet address? I don't quite understand, let's take 2miners for example.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NebuTech/NBMiner"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月19日(星期五) 晚上8:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [NebuTech/NBMiner] 开发费是否会用代理? (Issue #633)





 
设置 -proxy 的话，fee也会跟着走
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
