### ISSUE TITLE
[feature]Ethereum stratum mode

### ISSUE THREAD

**Issue by dazgluk** [NebuTech/NBMiner#77]
Hello.
I'm unable to dual mine ETH+BTM miner only support ethproxy+tcp pool connection, however most pools support only stratum+tcp these days (ethermine, nanopool)

Please add stratum+tcp to ethereum

**Comment by toptim** [comment]
not work with f2pool too
what number write to --secondary-intensity for 1070 or 1070ti?

**Comment by nebutech-admin** [comment]
The "ethproxy mode" in v12.0 works well on ethermine, f2pool(8008), nanopool.
More protocols (stratum, nicehash) will be implemented in the next version soon.

**Comment by toptim** [comment]
can you show example of config.json for "ethproxy mode" in v12.0
and what number write to --secondary-intensity for 1070 or 1070ti?
thanks

**Comment by nebutech-admin** [comment]
@toptim Did you use the Linux version?

I'd forgot to add a sample config file in Linux tarball.

There is a sample `config.json` in windows version .zip file.

You can use that as an example.

**Comment by nebutech-admin** [comment]
@toptim As described in `readme.md`, the recommend `-di` is 8 - 24.

By default, `-di`  is 16. 

If you want more hashrate on `tensority` than `ethash`, decrease `-di`, otherwise increase it.

The "best" `-di` varies between different cards. General speaking, the most profitable `-di`, by hashrate improvement, not by fiat profit, is when the memory utilization get jsut right on 100%.

**Comment by toptim** [comment]
Thanks
Use linux version
